# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_v5.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1212, 951)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolBox = QtWidgets.QToolBox(self.tab)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 1152, 788))
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableView(self.page)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 1152, 788))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView_2 = QtWidgets.QTableView(self.page_2)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_3.addWidget(self.tableView_2)
        self.toolBox.addItem(self.page_2, "")
        self.horizontalLayout_2.addWidget(self.toolBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.toolBox_2 = QtWidgets.QToolBox(self.tab_2)
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableView_3 = QtWidgets.QTableView(self.page_3)
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout_4.addWidget(self.tableView_3)
        self.toolBox_2.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_4.setObjectName("page_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableView_4 = QtWidgets.QTableView(self.page_4)
        self.tableView_4.setObjectName("tableView_4")
        self.verticalLayout_5.addWidget(self.tableView_4)
        self.toolBox_2.addItem(self.page_4, "")
        self.page_29 = QtWidgets.QWidget()
        self.page_29.setObjectName("page_29")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.page_29)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.tableView_29 = QtWidgets.QTableView(self.page_29)
        self.tableView_29.setObjectName("tableView_29")
        self.verticalLayout_42.addWidget(self.tableView_29)
        self.toolBox_2.addItem(self.page_29, "")
        self.verticalLayout_6.addWidget(self.toolBox_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.toolBox_3 = QtWidgets.QToolBox(self.tab_3)
        self.toolBox_3.setObjectName("toolBox_3")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_5.setObjectName("page_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableView_5 = QtWidgets.QTableView(self.page_5)
        self.tableView_5.setObjectName("tableView_5")
        self.verticalLayout_7.addWidget(self.tableView_5)
        self.toolBox_3.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 98, 89))
        self.page_6.setObjectName("page_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableView_6 = QtWidgets.QTableView(self.page_6)
        self.tableView_6.setObjectName("tableView_6")
        self.verticalLayout_8.addWidget(self.tableView_6)
        self.toolBox_3.addItem(self.page_6, "")
        self.page_30 = QtWidgets.QWidget()
        self.page_30.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_30.setObjectName("page_30")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.page_30)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.tableView_30 = QtWidgets.QTableView(self.page_30)
        self.tableView_30.setObjectName("tableView_30")
        self.verticalLayout_43.addWidget(self.tableView_30)
        self.toolBox_3.addItem(self.page_30, "")
        self.verticalLayout_31.addWidget(self.toolBox_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.toolBox_4 = QtWidgets.QToolBox(self.tab_4)
        self.toolBox_4.setObjectName("toolBox_4")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_7.setObjectName("page_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tableView_7 = QtWidgets.QTableView(self.page_7)
        self.tableView_7.setObjectName("tableView_7")
        self.verticalLayout_9.addWidget(self.tableView_7)
        self.toolBox_4.addItem(self.page_7, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 98, 89))
        self.page_8.setObjectName("page_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tableView_8 = QtWidgets.QTableView(self.page_8)
        self.tableView_8.setObjectName("tableView_8")
        self.verticalLayout_10.addWidget(self.tableView_8)
        self.toolBox_4.addItem(self.page_8, "")
        self.page_31 = QtWidgets.QWidget()
        self.page_31.setGeometry(QtCore.QRect(0, 0, 98, 89))
        self.page_31.setObjectName("page_31")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.page_31)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.tableView_31 = QtWidgets.QTableView(self.page_31)
        self.tableView_31.setObjectName("tableView_31")
        self.verticalLayout_44.addWidget(self.tableView_31)
        self.toolBox_4.addItem(self.page_31, "")
        self.verticalLayout_32.addWidget(self.toolBox_4)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.toolBox_5 = QtWidgets.QToolBox(self.tab_5)
        self.toolBox_5.setObjectName("toolBox_5")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_9.setObjectName("page_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tableView_9 = QtWidgets.QTableView(self.page_9)
        self.tableView_9.setObjectName("tableView_9")
        self.verticalLayout_11.addWidget(self.tableView_9)
        self.toolBox_5.addItem(self.page_9, "")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 98, 89))
        self.page_10.setObjectName("page_10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tableView_10 = QtWidgets.QTableView(self.page_10)
        self.tableView_10.setObjectName("tableView_10")
        self.verticalLayout_12.addWidget(self.tableView_10)
        self.toolBox_5.addItem(self.page_10, "")
        self.page_32 = QtWidgets.QWidget()
        self.page_32.setGeometry(QtCore.QRect(0, 0, 98, 89))
        self.page_32.setObjectName("page_32")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.page_32)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.tableView_32 = QtWidgets.QTableView(self.page_32)
        self.tableView_32.setObjectName("tableView_32")
        self.verticalLayout_45.addWidget(self.tableView_32)
        self.toolBox_5.addItem(self.page_32, "")
        self.verticalLayout_33.addWidget(self.toolBox_5)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.toolBox_6 = QtWidgets.QToolBox(self.tab_6)
        self.toolBox_6.setObjectName("toolBox_6")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setGeometry(QtCore.QRect(0, 0, 1152, 788))
        self.page_11.setObjectName("page_11")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_11)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tableView_11 = QtWidgets.QTableView(self.page_11)
        self.tableView_11.setObjectName("tableView_11")
        self.verticalLayout_13.addWidget(self.tableView_11)
        self.toolBox_6.addItem(self.page_11, "")
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_12.setObjectName("page_12")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_12)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tableView_12 = QtWidgets.QTableView(self.page_12)
        self.tableView_12.setObjectName("tableView_12")
        self.verticalLayout_14.addWidget(self.tableView_12)
        self.toolBox_6.addItem(self.page_12, "")
        self.page_33 = QtWidgets.QWidget()
        self.page_33.setObjectName("page_33")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.page_33)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.tableView_33 = QtWidgets.QTableView(self.page_33)
        self.tableView_33.setObjectName("tableView_33")
        self.verticalLayout_46.addWidget(self.tableView_33)
        self.toolBox_6.addItem(self.page_33, "")
        self.verticalLayout_34.addWidget(self.toolBox_6)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.toolBox_7 = QtWidgets.QToolBox(self.tab_7)
        self.toolBox_7.setObjectName("toolBox_7")
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setGeometry(QtCore.QRect(0, 0, 1152, 788))
        self.page_15.setObjectName("page_15")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_15)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.tableView_15 = QtWidgets.QTableView(self.page_15)
        self.tableView_15.setObjectName("tableView_15")
        self.verticalLayout_17.addWidget(self.tableView_15)
        self.toolBox_7.addItem(self.page_15, "")
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_16.setObjectName("page_16")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page_16)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.tableView_16 = QtWidgets.QTableView(self.page_16)
        self.tableView_16.setObjectName("tableView_16")
        self.verticalLayout_18.addWidget(self.tableView_16)
        self.toolBox_7.addItem(self.page_16, "")
        self.page_34 = QtWidgets.QWidget()
        self.page_34.setObjectName("page_34")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.page_34)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.tableView_34 = QtWidgets.QTableView(self.page_34)
        self.tableView_34.setObjectName("tableView_34")
        self.verticalLayout_47.addWidget(self.tableView_34)
        self.toolBox_7.addItem(self.page_34, "")
        self.verticalLayout_35.addWidget(self.toolBox_7)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.toolBox_8 = QtWidgets.QToolBox(self.tab_8)
        self.toolBox_8.setObjectName("toolBox_8")
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setGeometry(QtCore.QRect(0, 0, 1152, 788))
        self.page_17.setObjectName("page_17")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.page_17)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.tableView_17 = QtWidgets.QTableView(self.page_17)
        self.tableView_17.setObjectName("tableView_17")
        self.verticalLayout_19.addWidget(self.tableView_17)
        self.toolBox_8.addItem(self.page_17, "")
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_18.setObjectName("page_18")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_18)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.tableView_18 = QtWidgets.QTableView(self.page_18)
        self.tableView_18.setObjectName("tableView_18")
        self.verticalLayout_20.addWidget(self.tableView_18)
        self.toolBox_8.addItem(self.page_18, "")
        self.page_35 = QtWidgets.QWidget()
        self.page_35.setObjectName("page_35")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout(self.page_35)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.tableView_35 = QtWidgets.QTableView(self.page_35)
        self.tableView_35.setObjectName("tableView_35")
        self.verticalLayout_48.addWidget(self.tableView_35)
        self.toolBox_8.addItem(self.page_35, "")
        self.verticalLayout_36.addWidget(self.toolBox_8)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.toolBox_9 = QtWidgets.QToolBox(self.tab_9)
        self.toolBox_9.setObjectName("toolBox_9")
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setGeometry(QtCore.QRect(0, 0, 1152, 788))
        self.page_19.setObjectName("page_19")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.page_19)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.tableView_19 = QtWidgets.QTableView(self.page_19)
        self.tableView_19.setObjectName("tableView_19")
        self.verticalLayout_21.addWidget(self.tableView_19)
        self.toolBox_9.addItem(self.page_19, "")
        self.page_20 = QtWidgets.QWidget()
        self.page_20.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_20.setObjectName("page_20")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.page_20)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.tableView_20 = QtWidgets.QTableView(self.page_20)
        self.tableView_20.setObjectName("tableView_20")
        self.verticalLayout_22.addWidget(self.tableView_20)
        self.toolBox_9.addItem(self.page_20, "")
        self.page_36 = QtWidgets.QWidget()
        self.page_36.setObjectName("page_36")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.page_36)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.tableView_36 = QtWidgets.QTableView(self.page_36)
        self.tableView_36.setObjectName("tableView_36")
        self.verticalLayout_49.addWidget(self.tableView_36)
        self.toolBox_9.addItem(self.page_36, "")
        self.verticalLayout_37.addWidget(self.toolBox_9)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.toolBox_10 = QtWidgets.QToolBox(self.tab_10)
        self.toolBox_10.setObjectName("toolBox_10")
        self.page_21 = QtWidgets.QWidget()
        self.page_21.setGeometry(QtCore.QRect(0, 0, 1152, 788))
        self.page_21.setObjectName("page_21")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.page_21)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.tableView_21 = QtWidgets.QTableView(self.page_21)
        self.tableView_21.setObjectName("tableView_21")
        self.verticalLayout_23.addWidget(self.tableView_21)
        self.toolBox_10.addItem(self.page_21, "")
        self.page_22 = QtWidgets.QWidget()
        self.page_22.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_22.setObjectName("page_22")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.page_22)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.tableView_22 = QtWidgets.QTableView(self.page_22)
        self.tableView_22.setObjectName("tableView_22")
        self.verticalLayout_24.addWidget(self.tableView_22)
        self.toolBox_10.addItem(self.page_22, "")
        self.page_37 = QtWidgets.QWidget()
        self.page_37.setObjectName("page_37")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout(self.page_37)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.tableView_37 = QtWidgets.QTableView(self.page_37)
        self.tableView_37.setObjectName("tableView_37")
        self.verticalLayout_50.addWidget(self.tableView_37)
        self.toolBox_10.addItem(self.page_37, "")
        self.verticalLayout_38.addWidget(self.toolBox_10)
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.tab_11)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.toolBox_11 = QtWidgets.QToolBox(self.tab_11)
        self.toolBox_11.setObjectName("toolBox_11")
        self.page_23 = QtWidgets.QWidget()
        self.page_23.setGeometry(QtCore.QRect(0, 0, 1152, 788))
        self.page_23.setObjectName("page_23")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.page_23)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.tableView_23 = QtWidgets.QTableView(self.page_23)
        self.tableView_23.setObjectName("tableView_23")
        self.verticalLayout_25.addWidget(self.tableView_23)
        self.toolBox_11.addItem(self.page_23, "")
        self.page_24 = QtWidgets.QWidget()
        self.page_24.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_24.setObjectName("page_24")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.page_24)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.tableView_24 = QtWidgets.QTableView(self.page_24)
        self.tableView_24.setObjectName("tableView_24")
        self.verticalLayout_26.addWidget(self.tableView_24)
        self.toolBox_11.addItem(self.page_24, "")
        self.page_38 = QtWidgets.QWidget()
        self.page_38.setObjectName("page_38")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout(self.page_38)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.tableView_38 = QtWidgets.QTableView(self.page_38)
        self.tableView_38.setObjectName("tableView_38")
        self.verticalLayout_51.addWidget(self.tableView_38)
        self.toolBox_11.addItem(self.page_38, "")
        self.verticalLayout_39.addWidget(self.toolBox_11)
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.tab_12)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.toolBox_12 = QtWidgets.QToolBox(self.tab_12)
        self.toolBox_12.setObjectName("toolBox_12")
        self.page_25 = QtWidgets.QWidget()
        self.page_25.setGeometry(QtCore.QRect(0, 0, 1152, 788))
        self.page_25.setObjectName("page_25")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.page_25)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.tableView_25 = QtWidgets.QTableView(self.page_25)
        self.tableView_25.setObjectName("tableView_25")
        self.verticalLayout_27.addWidget(self.tableView_25)
        self.toolBox_12.addItem(self.page_25, "")
        self.page_26 = QtWidgets.QWidget()
        self.page_26.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_26.setObjectName("page_26")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.page_26)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.tableView_26 = QtWidgets.QTableView(self.page_26)
        self.tableView_26.setObjectName("tableView_26")
        self.verticalLayout_28.addWidget(self.tableView_26)
        self.toolBox_12.addItem(self.page_26, "")
        self.page_39 = QtWidgets.QWidget()
        self.page_39.setObjectName("page_39")
        self.verticalLayout_52 = QtWidgets.QVBoxLayout(self.page_39)
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.tableView_39 = QtWidgets.QTableView(self.page_39)
        self.tableView_39.setObjectName("tableView_39")
        self.verticalLayout_52.addWidget(self.tableView_39)
        self.toolBox_12.addItem(self.page_39, "")
        self.verticalLayout_40.addWidget(self.toolBox_12)
        self.tabWidget.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.tab_13)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.toolBox_13 = QtWidgets.QToolBox(self.tab_13)
        self.toolBox_13.setObjectName("toolBox_13")
        self.page_27 = QtWidgets.QWidget()
        self.page_27.setGeometry(QtCore.QRect(0, 0, 1152, 788))
        self.page_27.setObjectName("page_27")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.page_27)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.tableView_27 = QtWidgets.QTableView(self.page_27)
        self.tableView_27.setObjectName("tableView_27")
        self.verticalLayout_29.addWidget(self.tableView_27)
        self.toolBox_13.addItem(self.page_27, "")
        self.page_28 = QtWidgets.QWidget()
        self.page_28.setGeometry(QtCore.QRect(0, 0, 1152, 761))
        self.page_28.setObjectName("page_28")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.page_28)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.tableView_28 = QtWidgets.QTableView(self.page_28)
        self.tableView_28.setObjectName("tableView_28")
        self.verticalLayout_30.addWidget(self.tableView_28)
        self.toolBox_13.addItem(self.page_28, "")
        self.page_40 = QtWidgets.QWidget()
        self.page_40.setObjectName("page_40")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout(self.page_40)
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.tableView_40 = QtWidgets.QTableView(self.page_40)
        self.tableView_40.setObjectName("tableView_40")
        self.verticalLayout_53.addWidget(self.tableView_40)
        self.toolBox_13.addItem(self.page_40, "")
        self.verticalLayout_41.addWidget(self.toolBox_13)
        self.tabWidget.addTab(self.tab_13, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(12)
        self.toolBox.setCurrentIndex(1)
        self.toolBox_2.setCurrentIndex(0)
        self.toolBox_3.setCurrentIndex(0)
        self.toolBox_4.setCurrentIndex(0)
        self.toolBox_5.setCurrentIndex(0)
        self.toolBox_6.setCurrentIndex(2)
        self.toolBox_7.setCurrentIndex(2)
        self.toolBox_8.setCurrentIndex(2)
        self.toolBox_9.setCurrentIndex(2)
        self.toolBox_10.setCurrentIndex(2)
        self.toolBox_11.setCurrentIndex(2)
        self.toolBox_12.setCurrentIndex(2)
        self.toolBox_13.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_3), _translate("MainWindow", "Page 1"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_4), _translate("MainWindow", "Page 2"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_29), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_5), _translate("MainWindow", "Page 1"))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_6), _translate("MainWindow", "Page 2"))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_30), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.page_7), _translate("MainWindow", "Page 1"))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.page_8), _translate("MainWindow", "Page 2"))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.page_31), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.toolBox_5.setItemText(self.toolBox_5.indexOf(self.page_9), _translate("MainWindow", "Page 1"))
        self.toolBox_5.setItemText(self.toolBox_5.indexOf(self.page_10), _translate("MainWindow", "Page 2"))
        self.toolBox_5.setItemText(self.toolBox_5.indexOf(self.page_32), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Page"))
        self.toolBox_6.setItemText(self.toolBox_6.indexOf(self.page_11), _translate("MainWindow", "Page 1"))
        self.toolBox_6.setItemText(self.toolBox_6.indexOf(self.page_12), _translate("MainWindow", "Page 2"))
        self.toolBox_6.setItemText(self.toolBox_6.indexOf(self.page_33), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Page"))
        self.toolBox_7.setItemText(self.toolBox_7.indexOf(self.page_15), _translate("MainWindow", "Page 1"))
        self.toolBox_7.setItemText(self.toolBox_7.indexOf(self.page_16), _translate("MainWindow", "Page 2"))
        self.toolBox_7.setItemText(self.toolBox_7.indexOf(self.page_34), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Page"))
        self.toolBox_8.setItemText(self.toolBox_8.indexOf(self.page_17), _translate("MainWindow", "Page 1"))
        self.toolBox_8.setItemText(self.toolBox_8.indexOf(self.page_18), _translate("MainWindow", "Page 2"))
        self.toolBox_8.setItemText(self.toolBox_8.indexOf(self.page_35), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Page"))
        self.toolBox_9.setItemText(self.toolBox_9.indexOf(self.page_19), _translate("MainWindow", "Page 1"))
        self.toolBox_9.setItemText(self.toolBox_9.indexOf(self.page_20), _translate("MainWindow", "Page 2"))
        self.toolBox_9.setItemText(self.toolBox_9.indexOf(self.page_36), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Page"))
        self.toolBox_10.setItemText(self.toolBox_10.indexOf(self.page_21), _translate("MainWindow", "Page 1"))
        self.toolBox_10.setItemText(self.toolBox_10.indexOf(self.page_22), _translate("MainWindow", "Page 2"))
        self.toolBox_10.setItemText(self.toolBox_10.indexOf(self.page_37), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "Page"))
        self.toolBox_11.setItemText(self.toolBox_11.indexOf(self.page_23), _translate("MainWindow", "Page 1"))
        self.toolBox_11.setItemText(self.toolBox_11.indexOf(self.page_24), _translate("MainWindow", "Page 2"))
        self.toolBox_11.setItemText(self.toolBox_11.indexOf(self.page_38), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Page"))
        self.toolBox_12.setItemText(self.toolBox_12.indexOf(self.page_25), _translate("MainWindow", "Page 1"))
        self.toolBox_12.setItemText(self.toolBox_12.indexOf(self.page_26), _translate("MainWindow", "Page 2"))
        self.toolBox_12.setItemText(self.toolBox_12.indexOf(self.page_39), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "Page"))
        self.toolBox_13.setItemText(self.toolBox_13.indexOf(self.page_27), _translate("MainWindow", "Page 1"))
        self.toolBox_13.setItemText(self.toolBox_13.indexOf(self.page_28), _translate("MainWindow", "Page 2"))
        self.toolBox_13.setItemText(self.toolBox_13.indexOf(self.page_40), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("MainWindow", "Page"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
